$:
  vscode:
    - docker:
        image: cnbcool/default-dev-env:latest
      runner:
        cpus: 1
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: ls
          script: ls -al