$:
  vscode:
    - docker:
        image: cnbcool/default-dev-env:latest
      runner:
        cpus: 2
      services:
        - vscode
        - docker
      imports:
        # 引用密钥仓库文件
        - https://cnb.cool/dhjzz/pwd/-/blob/main/env.yml
      stages:
        - name: ls
          script: ls -al
        - name: merge
          script: sh ./scripts/merge.sh ${GITHUB_TOKEN}
